### ISSUE TITLE
Improve checking whether docker command returned success

### ISSUE THREAD

**Issue by kingsimmy** [bishtpawan/cargo-dockerimage#1]
Hi,
This tool is great.
One thing I noticed is that when I ran it without sudo the docker build command failed with exit code 1. This tool did not report the error in the log messages.

Would you be able to make an improvement in src/docker.rs around line 78 to match 
Ok(output) && output => SUCCESS_IMAGE ?

**Comment by bishtpawan** [comment]
Hi @kingsimmy,
Thanks for using and noticing the negative behavior of this tool.
Yes, I'll definitely look into this, and even it would be great if you can raise PR for the same for improving this tool.

**Comment by kingsimmy** [comment]
Fixed by https://github.com/bishtpawan/cargo-dockerimage/pull/2 and https://github.com/bishtpawan/cargo-dockerimage/pull/3
